### ISSUE TITLE
Feature: In-cluster exporter configuration 

### ISSUE THREAD

**Issue by hrytsai** [yonahd/kor#218] opened 2024-03-04 15:28 UTC
**Is your feature request related to a problem? Please describe.**
We run kor outside of the cluster with option provided below and got expected result: list of unused configmaps,secrets and pvc's in namespace
`kor configmap,secret,persistentvolumeclaim -n kor-test-namespace`
And now we want to reproduce this scenario but in cluster with export mode.

**Describe the solution you'd like**
Possibility to configure kor to export prometheus metric only from 1 namespace and reduce list of resources, for example only for: configmap,secret,persistentvolumeclaim in "In cluster" mode ?
Something like: 
`kor exporter -n columbus-data-platform-dev -r configmap,secret,persistentvolumeclaim (List of included resources, by default it can be: all)`

**Describe alternatives you've considered**

**Additional context**
We want use kor in environment where each project is isolated in own Project\Namespace in OpenShift 4.x platform and should keep tracking unused resources separately.

**Comment by Yuni-sa** [comment] 2024-03-10 09:04
@yonahd can I be assigned to this?

**Comment by yonahd** [comment] 2024-03-10 17:38
@Yuni-sa I believe namespaces are already supported

**Comment by Yuni-sa** [comment] 2024-03-10 17:45
@yonahd ,Yes it seems they do work as intended, I think I would add the functionality using GetUnusedMulti().

what do you think would be better:

```kor exporter svc,ing,pod -n namespace```
or 
``` kor exporter -r svc,ing,pod -n namespace```

**Comment by yonahd** [comment] 2024-03-10 20:00
I actually think the proper setup may be

`kor svc, ing -n namespace -exporter `

But using our current code we can do it with -r

**Closed** 2024-03-27 17:27 UTC
Labels: enhancement
