### ISSUE TITLE
Feature request: Support deletions of output

### ISSUE THREAD

**Issue by doryer** [yonahd/kor#42] opened 2023-08-30 09:53 UTC
As the CLI is supporting outputing unused resources which will lead probably to deletions for the cluster, i would like to have `--delete` flag which executes deletions on the output of the command, Example:

kor secrets -n default --delete

secret foo deleted

Also important to support deletions from all namespaces, will be useful for Cronjobs across the cluster

**Comment by yonahd** [comment] 2023-08-30 10:12
Duplicate of https://github.com/yonahd/kor/issues/38

**Closed by yonahd** 2023-08-30 10:12 UTC
